#!/usr/bin/env python3
"""Step 30 - assemble the manuscript tables.

Collects the per-step CSVs in ``results/tables/`` into the numbered
tables of the paper, rounds them to a sensible precision, and writes
both a machine-readable CSV and a Markdown rendering for pasting into
the manuscript. Also writes ``results/tables/README.md`` listing which
step produced each table, so the provenance of every number in the paper
is one file lookup away.

Run:  python workflow/30_assemble_tables.py
"""

from __future__ import annotations

import pandas as pd
from _common import step_setup

# table file -> (caption, producing step, columns to keep/round)
TABLES = {
    "table_S1_enso_events.csv": (
        "El Nino and La Nina events 1901-2019 with peak ONI, duration, "
        "amplitude class and EP/CP flavour.", "02"),
    "table_S2_isimip_availability.csv": (
        "ISIMIP3a model x variable x scenario availability.", "03"),
    "table_S3_file_inventory.csv": (
        "Input files used, with size and time coverage.", "05"),
    "table_S4_significance_summary.csv": (
        "Fraction of the land surface with a significant and robust "
        "composite response, per variable and event class.", "08"),
    "table_2_nonlinearity.csv": (
        "Nonlinear excess of the super-El-Nino response over a linearly "
        "scaled moderate/strong response, by variable and season.", "09"),
    "table_3_lag_cascade.csv": (
        "Lag of the peak response, response duration and AR(1) memory by "
        "variable.", "10"),
    "table_4_basin_amplification.csv": (
        "Super/reference amplification of the response by river basin.", "11"),
    "table_S5_basin_response.csv": (
        "Basin-mean composite anomalies with bootstrap intervals.", "11"),
    "table_5_lake_response.csv": (
        "Lake surface temperature and ice response by latitude band.", "12"),
    "table_S6_lake_ice.csv": ("Lake ice season changes by model.", "12"),
    "table_6_extremes.csv": (
        "Drought and flood months in event windows against the neutral "
        "baseline, with odds ratios.", "13"),
    "table_7_scenario_contrasts.csv": (
        "Contribution of background warming (obsclim - counterclim) and of "
        "water management (histsoc - nosoc) to the response.", "14"),
    "table_8_exposure.csv": (
        "Land area and population in cells with a robust response.", "15"),
    "table_9_model_evaluation.csv": (
        "Evaluation of the simulated composites against GRDC discharge, "
        "GRACE storage and satellite lake temperature.", "16"),
    "table_10_variance_partition.csv": (
        "Partition of the response variance between impact model, event and "
        "residual.", "17"),
    "table_S7_exposure_by_class.csv": (
        "Exposure by event class.", "15"),
    "table_S9_leave_one_out.csv": (
        "Sensitivity of the headline numbers to leaving out one model or one "
        "event.", "17"),
}


def to_markdown(df: pd.DataFrame, max_rows: int = 40) -> str:
    show = df.head(max_rows)
    try:
        md = show.to_markdown(index=False, floatfmt=".3g")
    except ImportError:      # tabulate not installed
        md = show.to_string(index=False)
    if len(df) > max_rows:
        md += f"\n\n_({len(df) - max_rows} further rows in the CSV)_\n"
    return md


def main() -> int:
    cfg, log, args = step_setup("30_assemble_tables", __doc__)
    tdir = cfg.path("tables", mkdir=True)

    lines = ["# Tables", "",
             "Every table is regenerated by the workflow; do not edit by hand.",
             "", "| file | produced by | caption |", "|---|---|---|"]
    md_parts = []
    found = missing = 0

    for name, (caption, step) in TABLES.items():
        path = tdir / name
        if not path.exists():
            log.warning("missing (step %s not run?): %s", step, name)
            missing += 1
            continue
        found += 1
        df = pd.read_csv(path)
        num = df.select_dtypes("number").columns
        df[num] = df[num].round(4)
        df.to_csv(path, index=False)
        lines.append(f"| `{name}` | step {step} | {caption} |")
        md_parts.append(f"### {name}\n\n*{caption}*\n\n{to_markdown(df)}\n")
        log.info("%-42s %4d rows x %2d cols", name, len(df), df.shape[1])

    if not args.dry_run:
        (tdir / "README.md").write_text("\n".join(lines) + "\n")
        (tdir / "all_tables.md").write_text(
            "# ENSO_Inwaters - all tables\n\n" + "\n".join(md_parts))
    log.info("%d table(s) assembled, %d missing", found, missing)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
